Magnificent Cloth Cottonmouth

medium

# MultiInvoker's _vaultUpdate() wont work due to revert in vault.update()

## Summary

MultiInvoke.sol should execute operations in batch for the user, but when trying to update a vault through this contract, the call will always fail, breaking core functionality. 

## Vulnerability Detail

The invoke() function of MultiInvoke.sol cales (if user desires) the _vaultUpdate() function.

https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-extensions/contracts/MultiInvoker.sol#L129

Inside of this _vaultUpdate() we call vault.update() in behalf of the sender.

https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-extensions/contracts/MultiInvoker.sol#L206

This wont work, because the vault.update function checks inside _update() if msg.sender is account, and will revert if msg.sender is not account or operator of factory. (there is no way currently to add the MultiInvoker as an operator)

```solidity
if (msg.sender != account && !IVaultFactory(address(factory())).operators(account, msg.sender))
revert VaultNotOperatorError();
```

https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-extensions/contracts/MultiInvoker.sol#L206

## Impact

Breaking of core functionality, MultiInvoke is not working as intended.

## Code Snippet

https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-extensions/contracts/MultiInvoker.sol#L129
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-extensions/contracts/MultiInvoker.sol#L206
https://github.com/sherlock-audit/2023-07-perennial/blob/main/perennial-v2/packages/perennial-extensions/contracts/MultiInvoker.sol#L206

## Tool used

Manual Review

## Recommendation

We recommend, adding extra permission for MultiInvoker to call _update() of vault.